version: "3"

services:

    walvis_server:
        working_dir: "/app"

        ports:
            - "9099:9099"

        expose:
            - 9099

        build:
            context: ./server
            dockerfile: Dockerfile

        command: bash -c "python3 app.py"

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    walvis_client:

        working_dir: "/app"

        build:
            context: ./client
            dockerfile: Dockerfile

        ports:
            - "3300:3300"

        expose:
            - 3300

        command: bash -c "npm run start"

        depends_on:
            - walvis_server
